---
- name: Update Aall packages on server
  hosts: all
  become: yes
  become_method: su

  tasks:

  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: full
