---
- name: Update All packages on server
  become: yes
  hosts: all

  tasks:

  - name: Run apt-get update
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: full